### ISSUE TITLE
How can i install

### ISSUE THREAD

**Issue by bl4ck0r** [JulianEberius/track-o-bot-ios#1]
Hello,

i can i install this app on my phone ?

**Comment by JulianEberius** [comment]
Hi,

Thanks for your interest in the app. Currently, since it is not yet published to the App Store, the only way to install it is via a Mac with XCode installed. The free version of the Apple Developer account is enough. So if you're still interested, I'd be happy to have a beta tester, and I can provide some more specific instructions :-) If not, you will have to wait at least  a couple of weeks, maybe months for me to submit the app to the App store.

Julian

**Comment by bl4ck0r** [comment]
Hi Julian! Thanks for your fast answer! I would love to see to bring this app on appstore ! Sure i will do the betatest! What i must do :D? Could i do it only from a mac or also from a windows pc ?

**Comment by bl4ck0r** [comment]
Ok installed the new xcode beta and if i try to run the program it says builed failed- also if i convert it to the new swift. what to do ? im on iphone 6 and new ios 9.x version

After convert it to new swift i got less errors. (it did it manually on open the file) i got 2 errors in TrackOBot.swift. 

"Cannot downcast from 'Any Obejct' to a more optional type 'NSDictionary?'
&
"Call can thwor, but it is not marked with 'try' and the error is not handled

**Comment by JulianEberius** [comment]
For the newer XCode you need to use the branch swift2-xcode7. That should solve those issues. I think I will merge with master in the near future, then you can switch back. 

Also, the state on Github is not very recent. I have a newer version with more features in my local development environment. Now that I know I have a tester, I can try to keep the Github repo more up-to-date.

Thanks for testing,
Julian

**Comment by bl4ck0r** [comment]
Thanks for making this app! So i tryed the other branch and got it on my phone! I entered token and name work without issue but if i enter a game it come "Error occured, game not saved"

Either if i enter WON/Lose or Coin/not coin

If i would enter wrong name or token would it give me an error ?

Feature:
- Need to get a Ranked and Unranked Button.
- Logout Button would be also good
- Complete STAT overview
- import my decks (i have entered much decks which i face) and if i want to enter a oppenent i want to choose not such as warlock i want to choose my created deck for example warlockZoo
- on what rank i have played this match

Maybe in your local version include a few of the wanted features and i can have this version and test this :) ?

**Comment by JulianEberius** [comment]
Yeah, could be a typo in the username or API key. The version on Github does not verify (try to log in) when you enter your credentials, so please double check them. However, the version on GitHub is also  several weeks old, so maybe there is another error. I may also switch the App from using the API token (which has only limited access to the TrackOBot data, as I just recently learned) to using the credential files that the Track-O-Bot desktop apps can provide via Settings->Account->Export. These credentials exported from the Desktop app allow full access to the API. I will get back to you as soon as I have a more mature version available for testing. 

About your requests: some of them are already implemented, some are on my own agenda, some are new, some require cooperation from stevschmid (TrackOBot author)... I will open separate issues for them, and close this issue (which was originally about installation) for now, since you managed to install the app.

**Comment by bl4ck0r** [comment]
Thank you very much ! could i get your version that i have for now a working version ? Double checked now the login credentials- all fine same error

**Comment by JulianEberius** [comment]
As I said, I'll get back to you. Need some free time and my private (not work) machine to upload that version ;-)

**Comment by bl4ck0r** [comment]
ok ! thank you man ! im really looking forward  !

**Comment by JulianEberius** [comment]
I have commited an up-to-date version to Github, now using the master branch. The login procedure has changed, but I documented the new way in the README and in the app's login view itself.

**Comment by bl4ck0r** [comment]
works like a charm ! niceeee !
